import type { Metadata } from "next";
import "./globals.css";
import { DashboardFooter } from "@/utils/DashboardUtils";

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` font-NotoSans `}>
        {children}
        
      </body>
    </html>
  );
}
